# Supabase configuration file

[project]
# Project ID and name
id = "notetree"
name = "NoteTree"

[api]
# API settings
port = 54321
schemas = ["public", "auth"]
extra_search_path = ["public", "auth"]
max_rows = 1000

[db]
# Database settings
port = 54322
major_version = 15

[studio]
# Studio settings
port = 54323

[auth]
# Auth settings
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173/**"]
jwt_expiry = 3600
refresh_token_expiry = 2592000

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.sms]
enable_signup = false
twilio_account_sid = ""
twilio_message_service_sid = ""
twilio_auth_token = ""
twilio_from = ""

[auth.external.google]
enabled = true
client_id = "your-google-client-id"
client_secret = "your-google-client-secret"
redirect_uri = "http://localhost:54321/auth/v1/callback"

[auth.external.github]
enabled = false
client_id = ""
client_secret = ""
redirect_uri = ""

[auth.external.azure]
enabled = false
client_id = ""
client_secret = ""
redirect_uri = ""

[auth.external.apple]
enabled = false
client_id = ""
client_secret = ""
redirect_uri = ""

[auth.external.discord]
enabled = false
client_id = ""
client_secret = ""
redirect_uri = ""

[auth.external.facebook]
enabled = false
client_id = ""
client_secret = ""
redirect_uri = ""

[auth.external.gitlab]
enabled = false
client_id = ""
client_secret = ""
redirect_uri = ""

[auth.external.linkedin]
enabled = false
client_id = ""
client_secret = ""
redirect_uri = ""

[auth.external.spotify]
enabled = false
client_id = ""
client_secret = ""
redirect_uri = ""

[auth.external.twitch]
enabled = false
client_id = ""
client_secret = ""
redirect_uri = ""

[auth.external.twitter]
enabled = false
client_id = ""
client_secret = ""
redirect_uri = ""

[auth.external.slack]
enabled = false
client_id = ""
client_secret = ""
redirect_uri = ""

[auth.external.workos]
enabled = false
client_id = ""
client_secret = ""
redirect_uri = ""
