services:
  # Development environment
  notetree-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: notetree_dev
    ports:
      - "5173:5173"  # Next.js
      - "3001:3001"  # NestJS
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    profiles:
      - dev
    restart: unless-stopped
    networks:
      - notetree-network

  # Production environment
  notetree-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notetree_prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    profiles:
      - prod
    restart: unless-stopped
    networks:
      - notetree-network

  # Database for development (optional)
  postgres-dev:
    image: postgres:15-alpine
    container_name: notetree_postgres_dev
    environment:
      POSTGRES_DB: notetree_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    profiles:
      - dev
    restart: unless-stopped
    networks:
      - notetree-network

networks:
  notetree-network:
    driver: bridge

volumes:
  postgres_dev_data:
